### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MC-Clutch** [TheCSDev/mc-no-unused-chunks#3]
The game crashes about every 15 minutes when the mod is in use
[2022-08-16-6.log.gz](https://github.com/TheCSDev/mc-no-unused-chunks/files/9354602/2022-08-16-6.log.gz)

**Comment by TheCSDev** [comment]
Hello. According to the log file you have provided, your crash appears to have been caused by the render thread, aka the game's renderer:
>  OpenGL debug message: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=49652 javaw.exe 64bit)'

followed by...

> [13:15:05] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to allocate memory for buffer data.'
[13:15:05] [Render thread/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[13:15:05] [Render thread/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'

And that is where the report abruptly ends.

Something is causing your renderer to run out of memory and abruptly crash as far as I understood. You mentioned it happening 15 minutes after launching the game? Perhaps there is a memory leak or something that is building up and taking up more and more memory, eventually crashing the game. I don't think this mod has anything to do with that, because all this mod does is tell the game not to save chunks that get generated unless they're modified after generating, as simple as that.

I am assuming because this is an out of memory renderer issue, the game failed to appropriately generate a crash report? If there is a [crash report](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report) or a [fatal error log](https://www.google.com/search?q=java+fatal+error+log), you can provide those as well. I will now take a look at the rest of the provided log to try and figure out if my mod is causing this somehow.

**Comment by TheCSDev** [comment]
After looking at the logs, I am not really able to pinpoint what main cause is. I did see that you are using the `ComplementaryShaders_v4.2.2` shader pack, and I thought.. perhaps there is a memory leak issue with the shader pack? Because like.. what if the shader pack assumes a newly generated chunks will never have to be re-generated? I don't really know. I will try playing the game with the same shader pack and the mod myself, and see if I get an out of memory crash. I don't really know if the shaderpack is an issue tho. Will see.

**Comment by TheCSDev** [comment]
Hello again, I have a question. Could you please provide more information about the crash in question? More specifically, what modpack you are using if you are using any, and if the issue has kept presiting? Basically any information that will allow me to recreate this crash myself. Also, does removing the mod from the mod list resolve the crash issue or not? Also, while the logs do contain the list of mods, there are like ~200 mods listed there, so me installing them one by one would not be an easy tak, which is why I am asking if you are using a mod pack, and which one it is.

Once again, I would like to thnak you for repoting this issue and providing the logs. Have a great day.

**Comment by TheCSDev** [comment]
No response.
