### ISSUE TITLE
Deleting pre-loaded chunks server-side

### ISSUE THREAD

**Issue by AhptIO** [TheCSDev/mc-no-unused-chunks#8]
Hello, I can't seem to figure out how to perform the "optimization" on preloaded chunks server-side. Is there a command that I'm missing? I only see two options in the configuration file, as well. Thanks for the help on this.

**Comment by TheCSDev** [comment]
Hello.
Unfortunately the deleing already exising chunks featrue is only available on the Minecraft client, and I'll explain why. As for the server, the best thing the mod can do is discard unused chunks as they are being generated. I know this is likely inconvenient, having to move the world to the client and optimizing the world from there, but it appears to be the only way.

There are actually two big reasons for why it can not be done server-side:
1. <ins>The world optimization feature is only available on the client.</ins>
Minecraft itself does not offer a way to optimize worlds server-side (see reason 2.). Now technically if you look at Minecraft's source code, you will see the `WorldUpdater` (the module that optimizes and updates worlds) is available server-side as well, but this is so the server can load worlds from older Minecraft versions (aka update worlds to the current version). That's all the module does server-side, and it does this before ever loading the world (because when you run a server, you obviously also load the world). And speaking of worlds being loaded, which is the opposite of what we need, the second reason is...
3. <ins>The world files must all be unloaded when performing this operation.</ins>
And by running a server, you are loading the world. This feature was built on top of the `WorldUpdater` module (the one you see when going to the "Optimize world" menu on the client). This module goes through all chunks in all region files of a given (unloaded) world, and then modifies the chunk data however it needs to. This mod adds on top of that by checking if a given chunk is uninhabited, and then tells the `WorldUpdater` to simply discard the chunk if it is, thus making the `WorldUpdater` remove unused chunks. Now of course, pulling this off while the world is loaded would require accounting for loaded chunks as well, which would complicate things a bit. And the thing is, when certain chunks are loaded, the region files of those chunks are loaded as well (meaning you can't modify them). To be honest, if it somehow was possible to pull it off while the world is loaded, I don't even know how that would be done.

So yeah, I wanted to mention those two things so you can hopefully get to see how the feature works and why it can not do what you want it to do (ngl I want that feature as well, ). Sorry again for the inconvenience, and have a great day.

Also did you mean "Deleting pre-loaded" in the issue title? If so, I could pin this issue for other to see in case anyone else ever wants to ask this question,

**Comment by AhptIO** [comment]
Thanks for that detailed response! I updated the title and feel free to pin it!
